package pipeline.constants

object PipelineConstants {
  val METRICS_CODE_SUCCESS_MSG = "SUCCESS"
  val METRICS_CODE_FAILURE_MSG = "FAILURE"
  val METRICS_CODE_IMPLEMENTATION_ERROR_MSG = "IMPLEMENTATION_ERROR"

  val METRICS_CODE_SUCCESS_CODE = "SUCCESS"
  val METRICS_CODE_FAILURE_CODE = "FAILURE"
  val METRICS_CODE_IMPLEMENTATION_ERROR_CODE = "IMPLEMENTATION_ERROR"
}
